---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pds03-backend
  name: pds03-backend
  namespace: default
spec:
  ports:
  - name: http
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: pds03-backend
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pds03-backend
  name: pds03-backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pds03-backend
  template:
    metadata:
      labels:
        app: pds03-backend
      name: pds03-backend
    spec:
      containers:
      - env:
        - name: SPRING_PORT
          value: "8081"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: db.username
              name: pds03-backend
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: db.password
              name: pds03-backend
        - name: DB_NAME
          value: d1mlk9fek4idsd
        - name: DB_HOST
          value: ec2-44-194-4-127.compute-1.amazonaws.com
        - name: DB_PORT
          value: "5432"
        image: cassa97/pds03-backend:v0.0.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 4
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: pds03-backend
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
