version: '3'

services:
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - data-postgresql-pds03-backend:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pds03-backend
  pgadmin:
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8081:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "db:pgsql-server"
  app:
    build: .
    ports:
      - 8080:8080
    env_file:
      - ./deploy/dev.env
    depends_on:
      - db
volumes:
  data-postgresql-pds03-backend:
  pgadmin-data:
