-- Recommendation: Execute script in order.

-- Persons:
INSERT INTO persons (dni, email, first_name, last_name, role, legajo) VALUES ('11111111', 'alumno@gmail.com', 'alumno', 'alumno', 1, '34627');
INSERT INTO persons (dni, email, first_name, last_name, role, legajo) VALUES ('22222222', 'director@gmail.com', 'director', 'director', 2, null);

-- Users:
INSERT INTO users(username, person_id) VALUES ('alumno', 1);
INSERT INTO users(username, person_id) VALUES ('director', 2);

-- Degrees:
INSERT INTO degrees(acronym, name) VALUES ('TPI', 'Tecnicatura en Programación Informática');
INSERT INTO degrees(acronym, name) VALUES ('LI', 'Licenciatura en Informática');

-- Subjects:
INSERT INTO subjects(name) VALUES ('Lectura y escritura académica');
INSERT INTO subjects(name) VALUES ('Matemática');
INSERT INTO subjects(name) VALUES ('Elementos de programación y lógica');
INSERT INTO subjects(name) VALUES ('Matemática I');
INSERT INTO subjects(name) VALUES ('Introducción a la Programación');
INSERT INTO subjects(name) VALUES ('Organización de Computadoras');
INSERT INTO subjects(name) VALUES ('Estructuras de Datos');
INSERT INTO subjects(name) VALUES ('Programación con Objetos I');
INSERT INTO subjects(name) VALUES ('Bases de Datos');
INSERT INTO subjects(name) VALUES ('Matemática II');
INSERT INTO subjects(name) VALUES ('Programación con Objetos II');
INSERT INTO subjects(name) VALUES ('Redes de Computadoras');
INSERT INTO subjects(name) VALUES ('Sistemas Operativos');
INSERT INTO subjects(name) VALUES ('Programación Funcional');
INSERT INTO subjects(name) VALUES ('Construcción de Interfaces de Usuario');
INSERT INTO subjects(name) VALUES ('Algoritmos'); SOLO LIC
INSERT INTO subjects(name) VALUES ('Estrategias de Persistencia');
INSERT INTO subjects(name) VALUES ('Laboratorio de Sistemas Operativos y Redes');
INSERT INTO subjects(name) VALUES ('Análisis Matemático');
INSERT INTO subjects(name) VALUES ('Lógica y Programación');
INSERT INTO subjects(name) VALUES ('Elementos de Ingeniería de Software');
INSERT INTO subjects(name) VALUES ('Seguridad de la Información');
INSERT INTO subjects(name) VALUES ('Matemática III');
INSERT INTO subjects(name) VALUES ('Programación Concurrente');
INSERT INTO subjects(name) VALUES ('Ingeniería de Requerimientos');
INSERT INTO subjects(name) VALUES ('Práctica del Desarrollo de Software');
INSERT INTO subjects(name) VALUES ('Probabilidad y Estadística');
INSERT INTO subjects(name) VALUES ('Gestión de Proyectos de Software');
INSERT INTO subjects(name) VALUES ('Lenguajes Formales y Autómatas');
INSERT INTO subjects(name) VALUES ('Programación con Objetos III');
INSERT INTO subjects(name) VALUES ('Teoría de la Computación');
INSERT INTO subjects(name) VALUES ('Arquitectura de Software I');
INSERT INTO subjects(name) VALUES ('Sistemas Distribuidos');
INSERT INTO subjects(name) VALUES ('Características de Lenguajes de Programación');
INSERT INTO subjects(name) VALUES ('Arquitectura de Software II');
INSERT INTO subjects(name) VALUES ('Arquitectura de Computadoras');
INSERT INTO subjects(name) VALUES ('Parseo y generación de código');
INSERT INTO subjects(name) VALUES ('Aspectos Legales y Sociales');
INSERT INTO subjects(name) VALUES ('Bases de Datos II');
INSERT INTO subjects(name) VALUES ('Participación y Gestión en Proyectos de Software Libre');
INSERT INTO subjects(name) VALUES ('Introducción a la Bioinformática');
INSERT INTO subjects(name) VALUES ('Políticas Públicas en la Sociedad de la Información y la Era Digital');
INSERT INTO subjects(name) VALUES ('Sistemas de Información Geográfica');
INSERT INTO subjects(name) VALUES ('Herramientas Declarativas en Programación');
INSERT INTO subjects(name) VALUES ('Introducción al Desarrollo de Videojuegos');
INSERT INTO subjects(name) VALUES ('Derechos de Autor y Derechos de Copia en la Era Digital');
INSERT INTO subjects(name) VALUES ('Análisis Estático de Programas y Herramientas Asociadas');
INSERT INTO subjects(name) VALUES ('Seminarios');
INSERT INTO subjects(name) VALUES ('Semántica de Lenguajes de Programación');
INSERT INTO subjects(name) VALUES ('Seminarios sobre Herramientas o Técnicas Puntuales');
INSERT INTO subjects(name) VALUES ('Taller de Trabajo Intelectual');
INSERT INTO subjects(name) VALUES ('Taller de Trabajo Universitario');
INSERT INTO subjects(name) VALUES ('Inglés I');
INSERT INTO subjects(name) VALUES ('Inglés II');
INSERT INTO subjects(name) VALUES ('Desarrollo de Aplicaciones');

INSERT INTO degree_subject(degree_id, subject_id) VALUES (1, 1);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (2, 1);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (1, 2);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (2, 2);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (1, 3);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (2, 3);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (1, 4);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (2, 4);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (1, 5);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (2, 5);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (1, 6);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (2, 6);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (1, 7);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (2, 7);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (1, 8);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (2, 8);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (1, 9);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (2, 9);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (1, 10);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (2, 10);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (1, 11);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (2, 11);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (1, 12);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (2, 12);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (1, 13);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (2, 13);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (1, 14);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (2, 14);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (1, 15);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (2, 15);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (2, 16);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (1, 17);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (2, 17);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (1, 18);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (2, 18);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (2, 19);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (2, 20);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (1, 21);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (2, 21);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (2, 22);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (2, 23);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (1, 24);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (2, 24);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (2, 25);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (2, 26);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (2, 27);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (2, 28);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (2, 29);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (2, 30);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (2, 31);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (2, 32);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (2, 33);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (2, 34);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (2, 35);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (2, 36);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (2, 37);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (2, 38);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (1, 39);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (2, 39);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (1, 40);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (2, 40);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (1, 41);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (2, 41);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (1, 42);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (2, 42);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (1, 43);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (2, 43);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (1, 44);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (2, 44);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (1, 45);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (2, 45);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (1, 46);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (2, 46);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (1, 47);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (2, 47);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (1, 48);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (2, 48);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (1, 49);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (2, 49);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (1, 50);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (2, 50);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (1, 51);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (2, 51);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (1, 52);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (2, 52);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (1, 53);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (2, 53);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (1, 54);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (2, 54);
INSERT INTO degree_subject(degree_id, subject_id) VALUES (1, 55);

-- Semesters:
INSERT INTO semesters(name, is_snd_semester, year) VALUES ('Primer cuatrimestre', false, 2022);

-- Courses:
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Susana Grillo', 'Lectura y escritura académica - Comisión 1', 30, 1, 1);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Susana Grillo', 'Lectura y escritura académica - Comisión 2', 32, 1, 1);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Alexander', 'Matemática - Comisión 1', 30, 1, 2);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Alexander', 'Matemática - Comisión 2', 32, 1, 2);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Flavia Saldaño', 'Elementos de programación y lógica - Comisión 1', 30, 1, 3);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Flavia Saldaño', 'Elementos de programación y lógica - Comisión 2', 32, 1, 3);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Susana', 'Matemática I - Comisión 1', 30, 1, 4);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Susana', 'Matemática I - Comisión 2', 32, 1, 4);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Alan Rodas', 'Introducción a la Programación - Comisión 1', 30, 1, 5);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Alan Rodas', 'Introducción a la Programación - Comisión 2', 32, 1, 5);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Denise', 'Organización de Computadoras - Comisión 1', 30, 1, 6);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Denise', 'Organización de Computadoras - Comisión 2', 32, 1, 6);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Fidel', 'Estructuras de Datos - Comisión 1', 30, 1, 7);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Fidel', 'Estructuras de Datos - Comisión 2', 32, 1, 7);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Maximo', 'Programación con Objetos I - Comisión 1', 30, 1, 8);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Maximo', 'Programación con Objetos I - Comisión 2', 32, 1, 8);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Gabriela Arévalo', 'Bases de Datos - Comisión 1', 30, 1, 9);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Gabriela Arévalo', 'Bases de Datos - Comisión 2', 32, 1, 9);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Jano', 'Matemática II - Comisión 1', 30, 1, 10);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Jano', 'Matemática II - Comisión 2', 32, 1, 10);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Diego T', 'Programación con Objetos II - Comisión 1', 30, 1, 11);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Diego T', 'Programación con Objetos II - Comisión 2', 32, 1, 11);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Cesar', 'Redes de Computadoras - Comisión 1', 30, 1, 12);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Cesar', 'Redes de Computadoras - Comisión 2', 32, 1, 12);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Mardelo', 'Sistemas Operativos - Comisión 1', 30, 1, 13);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Mardelo', 'Sistemas Operativos - Comisión 2', 32, 1, 13);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Fidel', 'Programación Funcional - Comisión 1', 30, 1, 14);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Fidel', 'Programación Funcional - Comisión 2', 32, 1, 14);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Martin', 'Construcción de Interfaces de Usuario - Comisión 1', 30, 1, 15);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Martin', 'Construcción de Interfaces de Usuario - Comisión 2', 32, 1, 15);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Pablo Facto', 'Algoritmos - Comisión 1', 30, 1, 16);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Pablo Facto', 'Algoritmos - Comisión 2', 32, 1, 16);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Ronny', 'Estrategias de Persistencia - Comisión 1', 30, 1, 17);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Ronny', 'Estrategias de Persistencia - Comisión 2', 32, 1, 17);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Jose Luis', 'Laboratorio de Sistemas Operativos y Redes - Comisión 1', 30, 1, 18);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Jose Luis', 'Laboratorio de Sistemas Operativos y Redes - Comisión 2', 32, 1, 18);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Claudia', 'Análisis Matemático - Comisión 1', 30, 1, 19);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Claudia', 'Análisis Matemático - Comisión 2', 32, 1, 19);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Ema Arevalo', 'Lógica y Programación - Comisión 1', 30, 1, 20);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Ema Arevalo', 'Lógica y Programación - Comisión 2', 32, 1, 20);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Pablo Suarez', 'Elementos de Ingeniería de Software - Comisión 1', 30, 1, 21);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Pablo Suarez', 'Elementos de Ingeniería de Software - Comisión 2', 32, 1, 21);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Fede', 'Seguridad de la Información - Comisión 1', 30, 1, 22);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Fede', 'Seguridad de la Información - Comisión 2', 32, 1, 22);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Claudia', 'Matemática III - Comisión 1', 30, 1, 23);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Claudia', 'Matemática III - Comisión 2', 32, 1, 23);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Dani', 'Programación Concurrente - Comisión 1', 30, 1, 24);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Dani', 'Programación Concurrente - Comisión 2', 32, 1, 24);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Pepe Grillo', 'Ingeniería de Requerimientos - Comisión 1', 30, 1, 25);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Pepe Grillo', 'Ingeniería de Requerimientos - Comisión 2', 32, 1, 25);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Gabriela Arévalo', 'Práctica del Desarrollo de Software - Comisión 1', 30, 1, 26);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Gabriela Arévalo', 'Práctica del Desarrollo de Software - Comisión 2', 32, 1, 26);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Jano', 'Probabilidad y Estadística - Comisión 1', 30, 1, 27);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Jano', 'Probabilidad y Estadística - Comisión 2', 32, 1, 27);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Pepe Grillo', 'Gestión de Proyectos de Software - Comisión 1', 30, 1, 28);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Pepe Grillo', 'Gestión de Proyectos de Software - Comisión 2', 32, 1, 28);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Ema Arevalo', 'Lenguajes Formales y Autómatas - Comisión 1', 30, 1, 29);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Ema Arevalo', 'Lenguajes Formales y Autómatas - Comisión 2', 32, 1, 29);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Diego T', 'Programación con Objetos III - Comisión 1', 30, 1, 30);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Diego T', 'Programación con Objetos III - Comisión 2', 32, 1, 30);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Jano', 'Teoría de la Computación - Comisión 1', 30, 1, 31);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Jano', 'Teoría de la Computación - Comisión 2', 32, 1, 31);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Claudia', 'Arquitectura de Software I - Comisión 1', 30, 1, 32);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Claudia', 'Arquitectura de Software I - Comisión 2', 32, 1, 32);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Marcelo', 'Sistemas Distribuidos - Comisión 1', 30, 1, 33);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Marcelo', 'Sistemas Distribuidos - Comisión 2', 32, 1, 33);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Jano', 'Características de Lenguajes de Programación - Comisión 1', 30, 1, 34);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Jano', 'Características de Lenguajes de Programación - Comisión 2', 32, 1, 34);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Juan Perez', 'Arquitectura de Software II - Comisión 1', 30, 1, 35);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Juan Perez', 'Arquitectura de Software II - Comisión 2', 32, 1, 35);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Susana', 'Arquitectura de Computadoras - Comisión 1', 30, 1, 36);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Susana', 'Arquitectura de Computadoras - Comisión 2', 32, 1, 36);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Juan Perez', 'Parseo y generación de código - Comisión 1', 30, 1, 37);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Juan Perez', 'Parseo y generación de código - Comisión 2', 32, 1, 37);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Lucas', 'Aspectos Legales y Sociales - Comisión 1', 30, 1, 38);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Lucas', 'Aspectos Legales y Sociales - Comisión 2', 32, 1, 38);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Gabriela Arévalo', 'Bases de Datos II - Comisión 1', 30, 1, 39);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Gabriela Arévalo', 'Bases de Datos II - Comisión 2', 32, 1, 39);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Gabriela Arévalo', 'Participación y Gestión en Proyectos de Software Libre - Comisión 1', 30, 1, 40);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Gabriela Arévalo', 'Participación y Gestión en Proyectos de Software Libre - Comisión 2', 32, 1, 40);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Juliana', 'Introducción a la Bioinformática - Comisión 1', 30, 1, 41);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Juliana', 'Introducción a la Bioinformática - Comisión 2', 32, 1, 41);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Fede Sawady', 'Políticas Públicas en la Sociedad de la Información y la Era Digital - Comisión 1', 30, 1, 42);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Fede Sawady', 'Políticas Públicas en la Sociedad de la Información y la Era Digital - Comisión 2', 32, 1, 42);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Flavia Saldaña', 'Sistemas de Información Geográfica - Comisión 1', 30, 1, 43);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Flavia Saldaña', 'Sistemas de Información Geográfica - Comisión 2', 32, 1, 43);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Jano', 'Herramientas Declarativas en Programación - Comisión 1', 30, 1, 44);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Jano', 'Herramientas Declarativas en Programación - Comisión 2', 32, 1, 44);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Diego T', 'Introducción al Desarrollo de Videojuegos - Comisión 1', 30, 1, 45);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Diego T', 'Introducción al Desarrollo de Videojuegos - Comisión 2', 32, 1, 45);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Marcelo', 'Derechos de Autor y Derechos de Copia en la Era Digital - Comisión 1', 30, 1, 46);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Marcelo', 'Derechos de Autor y Derechos de Copia en la Era Digital - Comisión 2', 32, 1, 46);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Fede Sawady', 'Análisis Estático de Programas y Herramientas Asociadas - Comisión 1', 30, 1, 47);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Fede Sawady', 'Análisis Estático de Programas y Herramientas Asociadas - Comisión 2', 32, 1, 47);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Gabriela Arévalo', 'Seminarios - Comisión 1', 30, 1, 48);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Gabriela Arévalo', 'Seminarios - Comisión 2', 32, 1, 48);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Maximo', 'Semántica de Lenguajes de Programación - Comisión 1', 30, 1, 49);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Maximo', 'Semántica de Lenguajes de Programación - Comisión 2', 32, 1, 49);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Pepe Grillo', 'Seminarios sobre Herramientas o Técnicas Puntuales - Comisión 1', 30, 1, 50);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Pepe Grillo', 'Seminarios sobre Herramientas o Técnicas Puntuales - Comisión 2', 32, 1, 50);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Pepe Grillo', 'Taller de Trabajo Intelectual - Comisión 1', 30, 1, 51);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Pepe Grillo', 'Taller de Trabajo Intelectual - Comisión 2', 32, 1, 51);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Pepe Grillo', 'Taller de Trabajo Universitario - Comisión 1', 30, 1, 52);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Pepe Grillo', 'Taller de Trabajo Universitario - Comisión 2', 32, 1, 52);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Liliana', 'Inglés I - Comisión 1', 30, 1, 53);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Liliana', 'Inglés I - Comisión 2', 32, 1, 53);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Liliana', 'Inglés II - Comisión 1', 30, 1, 54);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Liliana', 'Inglés II - Comisión 2', 32, 1, 54);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Feli', 'Desarrollo de Aplicaciones - Comisión 1', 30, 1, 55);
INSERT INTO courses(assigned_teachers, name, total_quotes, semester_id, subject_id) VALUES ('Feli', 'Desarrollo de Aplicaciones - Comisión 2', 32, 1, 55);

-- Quote requests:
INSERT INTO quote_requests(comment, state, course_id, student_id) VALUES ('No puedo por horario de trabajo', 0, 1, 1);

-- Studied degrees:
INSERT INTO studied_degrees(coefficient, degree_id, student_id) VALUES (10, 1, 1)

-- Studied courses:
INSERT INTO studied_courses(mark, status, course_id, studied_degree_id) VALUES (10, 2, 1, 1)
INSERT INTO studied_courses(mark, status, course_id, studied_degree_id) VALUES (10, 2, 3, 1)
INSERT INTO studied_courses(mark, status, course_id, studied_degree_id) VALUES (10, 2, 5, 1)