CREATE TABLE studied_subject
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    subject_id        BIGINT,
    mark              INTEGER,
    status            INTEGER                                 NOT NULL,
    studied_degree_id BIGINT,
    CONSTRAINT pk_studied_subject PRIMARY KEY (id)
);

ALTER TABLE studied_subject
    ADD CONSTRAINT FK_STUDIED_SUBJECT_ON_STUDIEDDEGREE FOREIGN KEY (studied_degree_id) REFERENCES studied_degrees (id);

ALTER TABLE studied_subject
    ADD CONSTRAINT FK_STUDIED_SUBJECT_ON_SUBJECT FOREIGN KEY (subject_id) REFERENCES subjects (id);

ALTER TABLE studied_courses
DROP
CONSTRAINT fk5m8hjpnxxl1415t4dy39iuq3s;

ALTER TABLE studied_courses
DROP
CONSTRAINT fko5bw8dchfke19k9p4tvooyo7w;

DROP TABLE studied_courses CASCADE;

ALTER TABLE hours
DROP
COLUMN _from;

ALTER TABLE hours
DROP
COLUMN _to;

ALTER TABLE hours
    ADD _from TIME WITHOUT TIME ZONE NOT NULL;

ALTER TABLE hours
    ADD _to TIME WITHOUT TIME ZONE NOT NULL;

ALTER TABLE persons
    ALTER COLUMN role DROP NOT NULL;