CREATE TABLE news
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title        VARCHAR(255)                            NOT NULL,
    message      VARCHAR(255)                            NOT NULL,
    image_source VARCHAR(255)                            NOT NULL,
    image_alt    VARCHAR(255)                            NOT NULL,
    created_on   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_news PRIMARY KEY (id)
);