CREATE TABLE student_enrolled_course
(
    course_id  BIGINT NOT NULL,
    student_id BIGINT NOT NULL
);

CREATE TABLE student_enrolled_degree
(
    degree_id  BIGINT NOT NULL,
    student_id BIGINT NOT NULL
);

CREATE TABLE studied_subjects
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    subject_id        BIGINT,
    mark              INTEGER,
    status            INTEGER                                 NOT NULL,
    studied_degree_id BIGINT,
    CONSTRAINT pk_studied_subjects PRIMARY KEY (id)
);

ALTER TABLE hours
    ADD _day INTEGER;

ALTER TABLE hours
ALTER
COLUMN _day SET NOT NULL;

ALTER TABLE semesters
    ADD accept_quote_requests_from TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE semesters
    ADD accept_quote_requests_to TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE quote_requests
    ADD admin_comment VARCHAR(255);

ALTER TABLE quote_requests
    ADD created_on TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE quote_requests
    ALTER COLUMN admin_comment SET NOT NULL;

ALTER TABLE quote_requests
    ALTER COLUMN created_on SET NOT NULL;

ALTER TABLE users
    ADD dni VARCHAR(255);

ALTER TABLE users
    ADD email VARCHAR(255);

ALTER TABLE users
    ADD first_name VARCHAR(255);

ALTER TABLE users
    ADD last_name VARCHAR(255);

ALTER TABLE users
    ADD legajo VARCHAR(255);

ALTER TABLE users
    ADD role INTEGER;

ALTER TABLE users
    ALTER COLUMN dni SET NOT NULL;

ALTER TABLE users
    ALTER COLUMN email SET NOT NULL;

ALTER TABLE users
    ALTER COLUMN first_name SET NOT NULL;

ALTER TABLE users
    ALTER COLUMN last_name SET NOT NULL;

UPDATE users
SET role = 'users'
WHERE role is null;

ALTER TABLE users
    ADD CONSTRAINT uc_users_dni UNIQUE (dni);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_legajo UNIQUE (legajo);

ALTER TABLE quote_requests
    ADD CONSTRAINT FK_QUOTE_REQUESTS_ON_STUDENT FOREIGN KEY (student_id) REFERENCES users (id);

ALTER TABLE studied_degrees
    ADD CONSTRAINT FK_STUDIED_DEGREES_ON_STUDENT FOREIGN KEY (student_id) REFERENCES users (id);

ALTER TABLE studied_subjects
    ADD CONSTRAINT FK_STUDIED_SUBJECTS_ON_STUDIEDDEGREE FOREIGN KEY (studied_degree_id) REFERENCES studied_degrees (id);

ALTER TABLE studied_subjects
    ADD CONSTRAINT FK_STUDIED_SUBJECTS_ON_SUBJECT FOREIGN KEY (subject_id) REFERENCES subjects (id);

ALTER TABLE student_enrolled_course
    ADD CONSTRAINT fk_stuenrcou_on_course FOREIGN KEY (course_id) REFERENCES courses (id);

ALTER TABLE student_enrolled_course
    ADD CONSTRAINT fk_stuenrcou_on_student FOREIGN KEY (student_id) REFERENCES users (id);

ALTER TABLE student_enrolled_degree
    ADD CONSTRAINT fk_stuenrdeg_on_degree FOREIGN KEY (degree_id) REFERENCES degrees (id);

ALTER TABLE student_enrolled_degree
    ADD CONSTRAINT fk_stuenrdeg_on_student FOREIGN KEY (student_id) REFERENCES users (id);

ALTER TABLE studied_subject
DROP
CONSTRAINT fk_studied_subject_on_studieddegree;

ALTER TABLE studied_subject
DROP
CONSTRAINT fk_studied_subject_on_subject;

ALTER TABLE studied_degrees
DROP
CONSTRAINT fklaq0ifouafx1yeneyj54s824w;

ALTER TABLE course_student
DROP
CONSTRAINT fklmsbddqkv96q4nijkrxuof3ug;

ALTER TABLE quote_requests
DROP
CONSTRAINT fklpcvpd0x7c714ifxdr191f3fd;

ALTER TABLE users
DROP
CONSTRAINT fkmvbq8q4vpi6csivw9wcnq6ho5;

ALTER TABLE course_student
DROP
CONSTRAINT fksow7pyajls077dq3b8w01f064;

DROP TABLE course_student CASCADE;

DROP TABLE persons CASCADE;

DROP TABLE studied_subject CASCADE;

ALTER TABLE hours
DROP
COLUMN day;

ALTER TABLE semesters
DROP
COLUMN name;

ALTER TABLE users
DROP
COLUMN person_id;