CREATE TABLE configurable_validation
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    validation INTEGER                                 NOT NULL,
    active     BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_configurable_validation PRIMARY KEY (id)
);

CREATE TABLE prerequisite_subjects
(
    prerequisite_subject_id BIGINT NOT NULL,
    subject_id              BIGINT NOT NULL
);

ALTER TABLE configurable_validation
    ADD CONSTRAINT uc_configurable_validation_validation UNIQUE (validation);

ALTER TABLE prerequisite_subjects
    ADD CONSTRAINT fk_presub_on_prerequisite_subject FOREIGN KEY (prerequisite_subject_id) REFERENCES subjects (id);

ALTER TABLE prerequisite_subjects
    ADD CONSTRAINT fk_presub_on_subject FOREIGN KEY (subject_id) REFERENCES subjects (id);