CREATE TABLE courses_hours
(
    course_id BIGINT NOT NULL,
    hours_id  BIGINT NOT NULL
);

CREATE TABLE hours
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    _from VARCHAR(255) NOT NULL,
    _to   VARCHAR(255) NOT NULL,
    day INTEGER                                 NOT NULL,
    CONSTRAINT pk_hours PRIMARY KEY (id)
);

ALTER TABLE semesters
    ADD is_snd_semester BOOLEAN;

ALTER TABLE semesters
    ALTER COLUMN is_snd_semester SET NOT NULL;

ALTER TABLE semesters
    ADD CONSTRAINT uc_346b40164d11273dd391e163f UNIQUE (is_snd_semester, year);

ALTER TABLE courses_hours
    ADD CONSTRAINT uc_courses_hours_hours UNIQUE (hours_id);

ALTER TABLE courses_hours
    ADD CONSTRAINT fk_couhou_on_course FOREIGN KEY (course_id) REFERENCES courses (id);

ALTER TABLE courses_hours
    ADD CONSTRAINT fk_couhou_on_hour FOREIGN KEY (hours_id) REFERENCES hours (id);

ALTER TABLE courses
DROP
COLUMN current_quotes;

ALTER TABLE courses
DROP
COLUMN number;

ALTER TABLE semesters
DROP
COLUMN semester;