CREATE TABLE external_degrees
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    degree_id    BIGINT,
    guarani_code VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_external_degrees PRIMARY KEY (id)
);

CREATE TABLE external_subjects
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    subject_id   BIGINT,
    guarani_code VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_external_subjects PRIMARY KEY (id)
);

CREATE TABLE modules
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_modules PRIMARY KEY (id)
);

CREATE TABLE modules_subjects
(
    degrees_id  BIGINT NOT NULL,
    subjects_id BIGINT NOT NULL
);

ALTER TABLE studied_subjects
    ADD date date;

ALTER TABLE studied_subjects
    ALTER COLUMN date SET NOT NULL;

ALTER TABLE courses
    ADD external_id VARCHAR(255);

ALTER TABLE courses
    ADD location VARCHAR(255);

ALTER TABLE courses
    ALTER COLUMN external_id SET NOT NULL;

ALTER TABLE studied_degrees
    ADD is_regular BOOLEAN;

ALTER TABLE studied_degrees
    ADD location VARCHAR(255);

ALTER TABLE studied_degrees
    ADD plan VARCHAR(255);

ALTER TABLE studied_degrees
    ADD quality INTEGER;

ALTER TABLE studied_degrees
    ADD registry_state INTEGER;

ALTER TABLE studied_degrees
    ALTER COLUMN is_regular SET NOT NULL;

ALTER TABLE courses
    ALTER COLUMN location SET NOT NULL;

ALTER TABLE studied_degrees
    ALTER COLUMN location SET NOT NULL;

ALTER TABLE subjects
    ADD module_id BIGINT;

ALTER TABLE users
    ADD password VARCHAR(255);

ALTER TABLE users
    ALTER COLUMN password SET NOT NULL;

ALTER TABLE studied_degrees
    ALTER COLUMN plan SET NOT NULL;

ALTER TABLE studied_degrees
    ALTER COLUMN quality SET NOT NULL;

ALTER TABLE studied_degrees
    ALTER COLUMN registry_state SET NOT NULL;

ALTER TABLE external_degrees
    ADD CONSTRAINT uc_external_degrees_guarani_code UNIQUE (guarani_code);

ALTER TABLE external_subjects
    ADD CONSTRAINT uc_external_subjects_guarani_code UNIQUE (guarani_code);

ALTER TABLE modules
    ADD CONSTRAINT uc_modules_name UNIQUE (name);

ALTER TABLE modules_subjects
    ADD CONSTRAINT uc_modules_subjects_subjects UNIQUE (subjects_id);

ALTER TABLE external_degrees
    ADD CONSTRAINT FK_EXTERNAL_DEGREES_ON_DEGREE FOREIGN KEY (degree_id) REFERENCES degrees (id);

ALTER TABLE external_subjects
    ADD CONSTRAINT FK_EXTERNAL_SUBJECTS_ON_SUBJECT FOREIGN KEY (subject_id) REFERENCES subjects (id);

ALTER TABLE subjects
    ADD CONSTRAINT FK_SUBJECTS_ON_MODULE FOREIGN KEY (module_id) REFERENCES modules (id);

ALTER TABLE modules_subjects
    ADD CONSTRAINT fk_modsub_on_module FOREIGN KEY (degrees_id) REFERENCES modules (id);

ALTER TABLE modules_subjects
    ADD CONSTRAINT fk_modsub_on_subject FOREIGN KEY (subjects_id) REFERENCES subjects (id);

ALTER TABLE users
DROP
COLUMN username;